# Data Cleaning
The set of steps used to prepare raw data so it can be reliably used for training or evaluating machine learning models. This includes fixing errors, handling missing values, removing duplicates, encoding categorical data, and detecting outliers. Good preprocessing improves model accuracy, reduces noise, and ensures the dataset represents the real problem correctly.

- Data collected
- Data needs to be processed into a useable format

- Fix data types
- Parse dates
- Remove duplicates
- Light missing value marking (but not full imputation)
- Basic text cleaning
- Basic filtering of corrupted rows
- Remove anomalies

In [1]:
import pandas as pd

games_df = pd.read_csv("data/nba_games_raw.csv",index_col=0)

In [2]:
games_df.head()

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False

In [3]:
def remove_cols(df, cols):
    for col in cols:
        del df[col]
    return df

In [4]:
def get_clean_df(df):
    df = df.sort_values("date")     #and sorting the data by date
    df = df.reset_index(drop=True)  #resetting the index and dropping the old index
    df = remove_cols(df, ["mp.1","mp_opp.1","index_opp"]) #removing unnecessary cols
    
    seasons = df['season'].unique()   # returns seasons in order of appearance
    last_three_seasons = seasons[-5:]   # get the last 5 seasons

    # Filter DataFrame
    df = df[df['season'].isin(last_three_seasons)]
    return df

In [5]:
def remove_null_values(df):
    nulls = pd.isnull(df)
    nulls = nulls.sum()
    nulls = nulls[nulls > 0]
    
    valid_columns = df.columns[~df.columns.isin(nulls.index)]   #all columns which dont contain null values
    df = df[valid_columns].copy()
    
    return df

In [6]:
df = get_clean_df(games_df)
df = remove_null_values(df)

In [7]:
df = df.dropna() #Drop all null/na values

In [8]:
df.head()

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
2630,240.0,39.0,75.0,0.520,13.0,19.0,0.684,22.0,22.0,1.000,...,50.0,29.7,150.0,133.0,UTA,104,0,2017,2016-10-25,True
2631,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,1.000,...,50.0,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False
2632,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,0.722,...,100.0,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False
2633,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,0.885,...,75.0,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True
2634,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,0.737,...,50.0,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True

In [9]:
df["date"]

2630     2016-10-25
2631     2016-10-25
2632     2016-10-25
2633     2016-10-25
2634     2016-10-25
            ...
10473    2019-06-07
10474    2019-06-10
10475    2019-06-10
10476    2019-06-13
10477    2019-06-13
Name: date, Length: 7848, dtype: object

In [13]:
df.to_csv("data/nba_games.csv")