# Modelling Preprocessing

This is the preprocessing applied in production.
- Train/test split
- Scaling (StandardScaler, MinMaxScaler, RobustScaler)
- Normalisation (L2 norm)
- Full imputation
- Outlier handling
- Pipeline creation (sklearn Pipelines, SageMaker Pipelines)

Scaling all the column values for training, making sure to remove values which are invalid for scaling

In [6]:
import pandas as pd

df = pd.read_pickle('df_nba_games.pkl')

In [7]:
df.head()

,season,date,team,team_opp,mp_10,fg_10,fga_10,fg%_10,3p_10,3pa_10,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,days_rested,days_rested_opp,won
2696,2017,2016-10-29,IND,CHI,252.5,42.0,95.5,0.4415,8.5,21.5,...,25.00,33.75,189.5,111.0,112.0,0.5,0.5,1.0,2.0,False
2681,2017,2016-10-29,NOP,SAS,240.0,42.5,96.0,0.4415,4.0,20.5,...,34.70,27.50,225.0,107.5,114.5,0.0,0.0,1.0,2.0,False
2692,2017,2016-10-29,ORL,CLE,240.0,33.5,92.0,0.3645,7.0,22.0,...,58.05,31.65,188.0,105.0,108.0,0.5,0.0,1.0,1.0,False
2709,2017,2016-10-30,DAL,HOU,252.5,40.0,92.0,0.4355,13.0,38.5,...,31.25,38.20,167.5,114.0,118.0,0.5,0.0,2.0,2.0,False
2702,2017,2016-10-30,LAL,OKC,240.0,38.5,86.5,0.4435,10.5,29.0,...,65.00,37.95,176.5,118.0,105.0,0.5,0.5,2.0,2.0,False

In [8]:
df.describe()

,season,mp_10,fg_10,fga_10,fg%_10,3p_10,3pa_10,3p%_10,ft_10,fta_10,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,days_rested,days_rested_opp
count,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,...,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000,7466.000000
mean,2017.998795,241.550202,39.851061,86.798273,0.460038,10.497868,29.325775,0.357568,17.499598,22.762324,...,8.715270,39.740021,34.675162,176.406474,118.002173,107.454716,0.499276,0.508051,2.069649,2.069247
std,0.816195,2.318255,2.434899,3.561456,0.022425,2.058405,5.121978,0.032882,2.667474,3.321188,...,2.312299,7.275871,2.849228,13.167441,4.849823,6.117640,0.135839,0.210002,0.691909,0.692046
min,2017.000000,240.000000,32.000000,73.000000,0.360500,3.500000,16.500000,0.189000,8.500000,12.000000,...,1.650000,18.200000,26.860000,122.500000,92.000000,85.500000,0.000000,0.000000,1.000000,1.000000
25%,2017.000000,240.000000,38.200000,84.400000,0.444100,9.100000,25.600000,0.336800,15.600000,20.500000,...,7.160625,34.410000,32.700000,167.000000,114.800000,103.100000,0.400000,0.400000,2.000000,2.000000
50%,2018.000000,240.000000,39.700000,86.800000,0.459200,10.300000,29.000000,0.356950,17.400000,22.600000,...,8.300000,39.090000,34.200000,175.800000,117.900000,107.333333,0.500000,0.500000,2.000000,2.000000
75%,2019.000000,242.500000,41.500000,89.100000,0.474900,11.700000,32.400000,0.378000,19.200000,25.000000,...,9.860000,44.267500,36.090000,185.100000,121.400000,111.541667,0.600000,0.700000,2.000000,2.000000
max,2019.000000,252.500000,54.000000,100.333333,0.560000,19.700000,50.900000,0.528500,30.333333,37.666667,...,26.560000,100.000000,50.200000,226.600000,137.500000,136.000000,1.000000,1.000000,4.000000,4.000000

In [9]:
from sklearn.preprocessing import MinMaxScaler

removed_columns = ["season", "date", "team", "team_opp", "won"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [11]:
df['won'] = df['won'].astype(int)

In [12]:
df.head()

,season,date,team,team_opp,mp_10,fg_10,fga_10,fg%_10,3p_10,3pa_10,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,days_rested,days_rested_opp,won
2696,2017,2016-10-29,IND,CHI,1.0,0.454545,0.823171,0.406015,0.308642,0.145349,...,0.083130,0.295201,0.643612,0.417582,0.524752,0.5,0.5,0.000000,0.333333,0
2681,2017,2016-10-29,NOP,SAS,0.0,0.477273,0.841463,0.406015,0.030864,0.116279,...,0.201711,0.027421,0.984630,0.340659,0.574257,0.0,0.0,0.000000,0.333333,0
2692,2017,2016-10-29,ORL,CLE,0.0,0.068182,0.695122,0.020050,0.216049,0.159884,...,0.487164,0.205227,0.629203,0.285714,0.445545,0.5,0.0,0.000000,0.000000,0
2709,2017,2016-10-30,DAL,HOU,1.0,0.363636,0.695122,0.375940,0.586420,0.639535,...,0.159535,0.485861,0.432277,0.483516,0.643564,0.5,0.0,0.333333,0.333333,0
2702,2017,2016-10-30,LAL,OKC,0.0,0.295455,0.493902,0.416040,0.432099,0.363372,...,0.572127,0.475150,0.518732,0.571429,0.386139,0.5,0.5,0.333333,0.333333,0

In [13]:
df.to_pickle('df_nba_games_processed.pkl')